#!/usr/bin/env python3
# coding: utf-8

"""GlyNet Code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XHzv-It0ezKcQpTJkQemXH4mprZojJgc
"""


result_dir = 'Results-Chiral-III-linear'
"""## Libraries"""

import math
import random
import time
import itertools
import os.path
import sys
import numpy
import pandas
import torch

"""## Learning Environment and Functions"""

torch.manual_seed(0) # Seed the PRNG from http://pytorch.org/docs/master/notes/randomness.html
# torch.set_deterministic()

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('using:', device)


# In[ ]:


"""### GlyNet - Architecture"""

class GlyNet(torch.nn.Module):
    """Set up the neural network.
    in_dim: Number of input neurons.
    hidden: Number of neurons in each hidden layer.
    out_dim: Number of output neurons.
    n_hidden_layers: Number of hidden layers. Default: 0"""

    def __init__(self, in_dim, out_dim, n_hidden_layers = 1, 
                       n_hidden_layer_neurons = 100, **extra):
        super(GlyNet, self).__init__()
        self.settings = locals()	# record local variables of interest
        del self.settings['__class__'], self.settings['self']
        del self.settings['extra']

        self.layers = torch.nn.ModuleList()   # init the neural net structures
        current_dim = in_dim
        for i in range(n_hidden_layers):
            self.layers.append(torch.nn.Linear(current_dim, n_hidden_layer_neurons))
            current_dim = n_hidden_layer_neurons
        self.layers.append(torch.nn.Linear(current_dim, out_dim))

    def forward(self, x):
        for i, layer in enumerate(self.layers):  #[:-1]):
            x = torch.nn.functional.leaky_relu(layer(x))
        #x = 0.5 + 0.5 * torch.nn.functional.tanh(self.layers[-1](x))
        return x
        # replace last layer with tanh instead of 

    def get_parameters(self):
        return self.settings          # report the recorded parameters


"""### Data Processing"""

def get_data(n_datasets = None, dataset_offset = 0, permute_seed = None,
             max_f_size = None, **extra):
    """Get IUPAC, finge  rprint and log RFU data."""

    parameters = locals()
    del parameters['extra']

    # load pre-processed output target values
    bind_data = pandas.read_csv('Data/f_values-50conc_Brewer3.tsv.gz', sep = '\t', 
                           index_col = 'Name', float_precision = 'round_trip')

    # load the molecular features table
    features = pandas.read_csv('Data/Morgan_fingerprints_Chiral_CFG+Biovia.tsv.gz',
                 sep = '\t', index_col = 'Name', float_precision = 'round_trip')

    # trim the feature table if maximum size given
    if max_f_size != None:
        keep_cols = [n for n in features.columns  if n[0] <= str(max_f_size)]
        features = features[keep_cols]

    # copy the features - once per concentration
    features_all = features.iloc[[],:]
    features_all.insert(loc = 0, column = 'Concentration', value = [])
    for concentration in [0.01, 0.1, 1.0, 10.0]:
        f_data = features
        f_data['Molecule_ID'] = '{} μM '.format(concentration) + f_data.index
        f_data = f_data.set_index('Molecule_ID')
        f_data.insert(loc = 0, column = 'Concentration', value = concentration)
        features_all = pandas.concat([features_all, f_data], axis = 0)
    features = features_all
    

    # quick hack to duplicate the features with an extra features table

    # load the molecular features table
    features_ext = pandas.read_csv('Data/Morgan_fingerprints_Chiral_CFG+Biovia_CFG+Biovia.tsv.gz',
                 sep = '\t', index_col = 'Name', float_precision = 'round_trip')

    # trim the feature table if maximum size given
    if max_f_size != None:
        keep_cols = [n for n in features_ext.columns  if n[0] <= str(max_f_size)]
        features_ext = features_ext[keep_cols]

    # copy the features - once per concentration
    features_all = features_ext.iloc[[],:]
    features_all.insert(loc = 0, column = 'Concentration', value = [])
    for concentration in [0.01, 0.1, 1.0, 10.0]:
        f_data = features_ext
        f_data['Molecule_ID'] = '{} μM '.format(concentration) + f_data.index
        f_data = f_data.set_index('Molecule_ID')
        f_data.insert(loc = 0, column = 'Concentration', value = concentration)
        features_all = pandas.concat([features_all, f_data], axis = 0)
    features_ext = features_all

###     rfu_data renamed bind_data
###    rfu_data = pd.read_csv('Data/Mean RFU.tsv',
###                               sep = '\t', float_precision = 'round_trip')
###    rfu_data2 = pd.read_csv('Data/Mean RFU Extension.tsv',
###                               sep = '\t', float_precision = 'round_trip')
###    rfu_data3 = pd.read_csv('Data/Mean RFU Extension 10uM.tsv',
###                               sep = '\t', float_precision = 'round_trip')
###    rfu_data = pd.concat([rfu_data, rfu_data2, rfu_data3], axis = 1)

###    rfu_data = rfu_data.drop('Name', axis = 1)


###    # exclude empty columns appended by MS Excel
###    rfu_data = rfu_data.iloc[:, [i  for i, x in enumerate(rfu_data.columns)  if not x.startswith('Unnamed: ')]]
###    print(rfu_data.columns)
###    #print(rfu_data)
### rfu_data = numpy.log(rfu_data)

    if n_datasets == None:
        n_datasets = bind_data.shape[1]
        parameters['n_datasets'] = n_datasets
    
    # obtain a reproducible (random-ish) permutation/subset of the data columns
    # defaults are the identity permutation and all the columns
    perm = list(range(bind_data.shape[1]))
    if permute_seed != None:
        prng = numpy.random.default_rng(seed = permute_seed)
        prng.shuffle(perm)
    bind_data = bind_data.iloc[:, perm[dataset_offset:dataset_offset+n_datasets]]

    # replace any NaNs in the binding data with -1
    bind_data[bind_data.isna()] = -1.0

    ### construct a features table with the rows and order of bind_data
    bind_data = features[[]].join(bind_data)
    features = bind_data[[]].join(features)
    if features.map(numpy.isnan).any().any():
        sys.stderr.write('Warning: Some molecule features are NaN!!!\n')

    # create the output data structures
    data = list(zip(bind_data.index, features.values, bind_data.values.tolist()))
    extra_data = list(zip(features_ext.index, features_ext.values))
    output_names = bind_data.columns.tolist()
    in_dim = features.shape[1]
    out_dim = bind_data.shape[1]

    print('Bind Data size:', bind_data.shape, features.shape) 
    return data, extra_data, output_names, in_dim, out_dim, parameters


# In[ ]:


def kfold_pnrg(data, parameters, fold_seed = None, n_folds = 10, n_samples = 10, **extra):
    """10-fold cross validation with random sampling.
    random_seed: To re-generate same random numbers. Default: None"""
    parameters.update(locals())
    del parameters['data']   # don't return the data argument as a parameter
    del parameters['extra']
    del parameters['parameters']
    
    # use a unique PRNG just for this function
    pnrg = numpy.random.default_rng(seed = fold_seed)
    
    # assign each fingerprint to one of ten random subsets
    #print('DDD:', data[0][1])
    fingerprint = dict.fromkeys([tuple(x[1][1:]) for x in data])
    key_list = list(fingerprint.keys())
    pnrg.shuffle(key_list)
    for i, x in enumerate(key_list):
        fingerprint[x] = i % n_folds 
    
    # data is held-out based on its fingerprint's random label
    # this ensures that training data does not contain glycans is the test set
    pnrg.shuffle(data)  # re-order the data
    for i in range(min(n_samples, n_folds)):
        hold_out = [x  for x in data  if fingerprint[tuple(x[1][1:])] == i]
        keep_in  = [x  for x in data  if fingerprint[tuple(x[1][1:])] != i]
        yield hold_out, keep_in

def prepare_data_old(data, batch_size = 64, mode = 'train', conc = None):
    """Prepare inputs and desired outputs for training or testing.
    weighted: To weight the data or not. Default: False.
    mode: Set to 'test' or 'train'. Default: 'train'."""

    fingpr_tensors, rfu_tensors = [], []
    for name, features, outputs in data:
        fingpr_tensor = torch.tensor(features).float().to(device)
        rfu_tensor = torch.tensor(outputs).float().to(device)
        fingpr_tensors.append(fingpr_tensor)
        rfu_tensors.append(rfu_tensor)

    if mode == 'train':
        trainset = list(zip(fingpr_tensors, rfu_tensors))
        return torch.utils.data.DataLoader(trainset, batch_size = batch_size)
    elif mode == 'test':
        fingpr_stack = torch.stack(fingpr_tensors).float().to(device)
        rfu_stack = torch.stack(rfu_tensors).float().to(device)
        return fingpr_stack, rfu_stack



def prepare_data_compare(data, batch_size = 64):
    """Prepare inputs and desired outputs for training or testing.
    weighted: To weight the data or not. Default: False.
    mode: Set to 'test'."""

    names, fingpr_tensors, rfu_tensors = [], [], []
    for name, features, outputs in data:
        names.append(name)
        fingpr_tensors.append(torch.tensor(features).float().to(device))
        rfu_tensors.append(torch.tensor(outputs).float().to(device))

    fingpr_stack = torch.stack(fingpr_tensors).float().to(device)
    rfu_stack = torch.stack(rfu_tensors).float().to(device)
    return names, fingpr_stack, rfu_stack

def prepare_data_eval(extra_data):
    """Prepare inputs and desired outputs for training or testing.
    weighted: To weight the data or not. Default: False.
    mode: Set to 'test'."""

    names, fingpr_tensors = [], []
    for name, features in extra_data:
        names.append(name)
        fingpr_tensors.append(torch.tensor(features).float().to(device))
        
    fingpr_stack = torch.stack(fingpr_tensors).float().to(device)
    return names, fingpr_stack



def prepare_data(data, batch_size = 64, mode = 'train'):
    """Prepare inputs and desired outputs for training or testing.
    weighted: To weight the data or not. Default: False.
    mode: Set to 'test' or 'train'. Default: 'train'."""

    tensors = []
    for name, features, values in data:
        input_tensor = torch.tensor(features).float().to(device)
        value_tensor = torch.tensor(values).float().to(device)

        tensors.append( (input_tensor, value_tensor) )

    return torch.utils.data.DataLoader(tensors, batch_size = batch_size)




"""### GlyNet - Training"""

def early_stop(losses, patience):
    """Return True if the loss hasn't improved for a number of epochs.
    patience: Number of epochs without improvement."""
    if min(losses) < min(losses[-patience:]):
        return True

def weighted_MSE(x, target, weights):
    """An alternation of calculating the data's MSE, in which we include the
    weights of the data. This function is adapted from
    https://discuss.pytorch.org/t/pixelwise-weights-for-mseloss/1254."""
    delta = x - target
    return ((delta * delta) * weights.expand_as(delta)).sum(0)

def myLoss(output, target):
    delta = (output - target) * (target > 0)
    loss = torch.mean(delta**2)
    return loss

def train(plot = False, weight_decay = 1e-4, patience = 10, torch_seed= 0,**kwargs):

#          fold_seed = None, n_samples = 1, 
#   n_hidden_neurons=100, n_hidden_layers=1, 
#          n_datasets = 1257, dataset_offset = 0, permute_seed = None

    """Train GlyNet using 10-fold cross-validation on the CFG data.
    n_hidden_neurons: Number of neurons in a each hidden layer. Default: 800.
    n_hidden_layers: Number of hidden layers. Default: 1.
    decay: Weight decay. Default: 1e-4.
    patience: Number of epochs without improvement. Default: 10.
    thres: Values below thres at set to thres. Default: None.
    n_cutoff: Number of values to be removed. Default: 0.
    weighted: To weight the data or not. Default: False.
    choice: Choice of sample. If None, all samples used. Default: None
    plot: Plot loss for every epoch. Default: False"""

    parameters = locals()
    del parameters['plot'], parameters['kwargs']

    data, extra_data, output_names, in_dim, out_dim, data_parameters = get_data(**kwargs)
    parameters.update(data_parameters)

    net = GlyNet(in_dim, out_dim, **kwargs).to(device)
    parameters.update(net.get_parameters())

    #print(in_dim, out_dim, n_hidden_neurons, n_hidden_layers)
    ###criterion = torch.nn.MSELoss()
    optimizer = torch.optim.Adam(net.parameters(), weight_decay = weight_decay)

    input_n   = numpy.zeros((0, in_dim),  dtype = numpy.float32)
    actual    = numpy.zeros((0, out_dim), dtype = numpy.float32)
    predicted = numpy.zeros((0, out_dim), dtype = numpy.float32)
    extra_eval= numpy.zeros((0, out_dim), dtype = numpy.float32)
    
    glycans, fold_num, extra_names_all = [], [], []
    for i, (held_out, kept_in) in enumerate(kfold_pnrg(data, parameters, **kwargs)):
        start_time = time.time()
        train_losses, test_losses = [], []
        trainloader = prepare_data(kept_in)
        print('Fold', i + 1, 'Held Out')
  
        # Initialize for per-fold training
        torch.manual_seed(torch_seed)
        for layers in net.children():
            for layer in layers:
                layer.reset_parameters()

        for epoch in range(1000):
            batch_loss = 0.0
            for inputs, values in trainloader:  ### prepare_data(kept_in):
                #print('Begin:', epoch)
                optimizer.zero_grad()
                outputs = net(inputs)
                ###loss = criterion(values, outputs)
                loss = myLoss(outputs, values)
                loss.backward()
                optimizer.step()
                batch_size, _ = values.size()
                batch_loss += loss.item() * batch_size
            train_loss = batch_loss / len(kept_in)
            train_losses.append(train_loss)

            ### check loss on the testing set
            names, test_inputs, test_values = prepare_data_compare(held_out)
            with torch.no_grad():
                test_outputs = net(test_inputs)
                ###test_loss = criterion(test_values, test_outputs)
                test_loss = myLoss(test_outputs, test_values)
            test_losses.append(test_loss.item())

            print('    Monitor: {} {} {} {}'.format(len(test_losses),
                      time.time() - start_time, train_loss, test_loss.item()))
            if early_stop(test_losses, patience):
                break

        # after all the training epochs - evaluate the extra dataset
        extra_names, extra_inputs = prepare_data_eval(extra_data)
        with torch.no_grad():
            extra_outputs = net(extra_inputs)

        glycans += [name for name, fingpr, rfu in held_out]
        fold_num += [i for x in held_out]
        input_n   = numpy.append(input_n,   test_inputs.numpy(),  axis = 0)
        actual    = numpy.append(actual,    test_values.numpy(),  axis = 0)
        predicted = numpy.append(predicted, test_outputs.numpy(), axis = 0)

        extra_names_all.extend(extra_names)
        extra_eval = numpy.append(extra_eval, extra_outputs.numpy(), axis = 0)

        print('Train Loss:', round(train_loss, 4))
        print('Test Loss:', round(test_loss.item(), 4))
        torch.save(net.state_dict(), '{}/trained_model-{}.pt'. format(result_dir, i))
        
    print('GlyNet Cross-Validation Complete')
 
    ###act_data  = pandas.DataFrame(actual, columns=output_names, index=glycans)
    ###pred_data = pandas.DataFrame(predicted, columns=output_names, index=glycans)
    input_data  = pandas.DataFrame(input_n, index=glycans)
    act_data    = pandas.DataFrame(actual, index=glycans, columns = output_names)
    pred_data   = pandas.DataFrame(predicted, index=glycans, columns = output_names)
    fold_data   = pandas.DataFrame(fold_num, index=glycans)

    print('EEEE:', len(extra_names_all), extra_eval.shape)
    extra_eval  = pandas.DataFrame(extra_eval, index = extra_names_all, columns = output_names)
    monitor_data = [time.time() - start_time, epoch, train_loss, test_loss]
   
    print('Sizes:', act_data.shape, pred_data.shape, fold_data.shape)
    ###print(act_data.iloc[0])
    ###print(pred_data.iloc[0])
 
    return input_data, act_data, pred_data, fold_data, monitor_data, extra_eval, parameters


# In[ ]:


"""### GlyNet - Results"""


# In[ ]:


# train and save results - override parameters for non-defaults
#def grid_iteration(n_hidden_layer_neurons = 100, n_hidden_layers = 1, weight_decay = 1e-4,
#                   batch_size = 64, fold_seed = 0, n_samples = 10, torch_seed = 0,
#                   n_cutoff = 200, subtree_depth = 3, terminals_used = True,
#                   n_datasets = 1257, dataset_offset = 0, permute_seed = None):
def grid_iteration(**parameters):
    #description = 'HL={n_hidden_layers} HN={n_hidden_layer_neurons} WD={weight_decay} FS={fold_seed} NC={n_cutoff} ND={n_datasets} OD={dataset_offset} SH={permute_seed}'.format(**parameters)
    # build a filename from the non-default parameters
    description = ' '.join(['{}={}'.format(k, v)   for k, v in parameters.items()])
    file_name = '{}/GlyNet {}.npz'.format(result_dir, description)  #time.ctime())
    print('Filename: {}'.format(file_name))

    if not os.path.exists(file_name):
        input_data, act_data, pred_data, fold_data, monitor_data, extra_eval, parameters_out = train(
                                                      plot = False, **parameters)
        unknowns = [k  for k in parameters.keys()  if k not in parameters_out]
        if len(unknowns) > 0:
            sys.stderr.write('Warning: Unknown parameter(s) {}\n'.format(unknowns))
        print('PPP:', parameters, parameters_out)

        # save arrays to one file - can be reloaded with numpy.load()
        with open(file_name, 'wb') as data_file:
            numpy.savez_compressed(data_file,
                  # save data - use format that do not require pickle() to load
                  parameters = numpy.array([(k, str(v))
                                              for k, v in parameters_out.items()]),
                  index = list(pred_data.index),
                  columns = list(pred_data.columns),
                  input_data = input_data.values,
                  act_data   = act_data.values,
                  pred_data  = pred_data.values,
                  fold_data  = fold_data.values,
                  extra_names= list(extra_eval.index),
                  extra_eval = extra_eval.values,
                  monitor_data = monitor_data)
        


# In[ ]:


#grid_iteration()

for f_size in range(3, 4):
    grid_iteration(max_f_size = f_size, n_hidden_layers = 2, weight_decay = 0.0)

grid_iteration(n_hidden_layers = 2, weight_decay = 0.0)
grid_iteration(n_hidden_layers = 1, weight_decay = 0.0)
grid_iteration(n_hidden_layers = 3, weight_decay = 0.0)
